const assert=require('node:assert/strict');
const path=require('node:path'),os=require('node:os');
const {chromium}=require(path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
const {createServer}=require('../server.cjs');
(async()=>{
 const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 const base='http://127.0.0.1:'+server.address().port;
 try{
  const context=await browser.newContext({viewport:{width:1280,height:800},hasTouch:true});
  await context.route('**/*',route=>route.request().url().startsWith(base)?route.continue():route.abort());
  const page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(base+'/question-manager.html');
  assert.equal(await page.locator('#managerQuestionList button').count(),10);
  await page.locator('#managerQuestionList button').first().tap();
  const original=await page.locator('#editorStem').inputValue();
  await page.locator('#editorStem').fill(original+' (수정 검사)');
  await page.getByRole('button',{name:'문제 저장',exact:true}).tap();
  assert.match(await page.locator('#managerStatus').textContent(),/저장했습니다/);
  await page.reload();await page.locator('#managerQuestionList button').first().tap();
  assert.equal(await page.locator('#editorStem').inputValue(),original+' (수정 검사)');
  await page.locator('#managerSection').selectOption('2');
  assert.ok(!(await page.locator('#editorStem').inputValue()).includes('(수정 검사)'));
  await page.getByRole('button',{name:'＋ 문제 추가',exact:true}).tap();
  await page.locator('#editorStem').fill('새 문항 저장 검사');
  for(let i=0;i<4;i++)await page.locator('#editorChoice'+i).fill('보기 '+(i+1));
  await page.locator('input[name=correct][value="2"]').check();await page.locator('#editorExplanation').fill('정답은 세 번째 보기입니다.');
  await page.getByRole('button',{name:'문제 저장',exact:true}).tap();assert.equal(await page.locator('#managerQuestionList button').count(),11);
  await page.getByRole('button',{name:'선택한 문제 삭제',exact:true}).tap();assert.equal(await page.locator('#managerQuestionList button').count(),10);
  // Validate import errors do not overwrite the existing bank.
  await page.locator('#importCourse').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"id":"broken"}')});
  await page.waitForFunction(()=>document.getElementById('managerStatus').textContent.includes('가져오기 실패'));
  assert.match(await page.locator('#managerStatus').textContent(),/가져오기 실패/);
  await page.setViewportSize({width:800,height:1280});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.screenshot({path:'tmp/question-manager-tablet.png',fullPage:true});
  const teacher=await context.newPage();teacher.on('pageerror',error=>errors.push(error.message));
  await teacher.goto(base+'/index.html?hostIp=127.0.0.1');
  await teacher.evaluate(()=>openMultiplayerModal());
  await teacher.locator('#classroomSubject').selectOption('사회');
  await teacher.locator('#classroomUnit').selectOption('social-6-2-1');
  await teacher.getByRole('button',{name:'➕ 선택한 단원으로 새 방 만들기',exact:true}).tap();
  assert.match(await teacher.locator('#displayRoomCode').textContent(),/^[12][0-9]{7}$/);
  assert.match(await teacher.locator('#classroomCurrentCourse').textContent(),/사회/);
  assert.match(await teacher.locator('#commonStudentUrl').textContent(),/student.html$/);
  await teacher.evaluate(()=>closeMultiplayerModal());
  assert.equal(await teacher.locator('.stage-card:not(.raid-card) h3').first().textContent(),'지형과 산지');
  const code=await teacher.locator('#displayRoomCode').textContent();await teacher.reload();
  await teacher.evaluate(()=>openMultiplayerModal());assert.equal(await teacher.locator('#displayRoomCode').textContent(),code);
  await teacher.screenshot({path:'tmp/subject-room-tablet.png',fullPage:true,animations:'disabled'});
  const modalBounds=await teacher.locator('#modalMultiplayer .modal-box').boundingBox();assert.ok(modalBounds.y>=0&&modalBounds.y+modalBounds.height<=800);
  const student=await context.newPage();student.on('pageerror',error=>errors.push(error.message));
  await student.goto(base+'/student.html');await student.waitForURL('**/index.html?role=student');
  assert.equal(await student.locator('#studentJoinRoomCode').inputValue(),'');
  assert.equal(await student.locator('#studentJoinRoomCode').getAttribute('readonly'),null);
  assert.equal(await student.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await student.screenshot({path:'tmp/student-code-tablet.png',fullPage:true});
  assert.deepEqual(errors,[]);
  console.log('PASS: manager edit/save/reload/section switch/add/delete/invalid import, tablet layouts, subject room creation, map labels, persistent room code, common student entry');
 }finally{await browser.close();server.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
